package com.nilsson.metadataviewer.service.strategy;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nilsson.metadataviewer.service.MetadataExtractionException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

/**
 * Metadata parsing strategy for NovelAI-generated images.
 * <p>
 * This strategy specializes in extracting generation parameters from the JSON structure
 * embedded in images generated by NovelAI. It maps NovelAI-specific keys (e.g., "uc" for
 * Undesired Content/Negative Prompt) to the application's standard metadata schema.
 * <p>
 * Key functionalities:
 * - JSON Parsing: Decodes the structured metadata block unique to NovelAI.
 * - Key Mapping: Translates "uc" to "Negative", "scale" to "CFG", and "sampler" to "Sampler".
 * - Software Identification: Explicitly identifies the originating software as "NovelAI Diffusion".
 * - Robust Extraction: Handles both textual and numeric values for parameters like steps and seeds.
 */
public class NovelAIStrategy implements MetadataStrategy {

    private static final Logger log = LoggerFactory.getLogger(NovelAIStrategy.class);
    private static final ObjectMapper mapper = new ObjectMapper();

    @Override
    public Map<String, String> parse(String text) {
        if (text == null || text.isBlank()) {
            return new HashMap<>();
        }

        Map<String, String> results = new HashMap<>();
        try {
            JsonNode root = mapper.readTree(text);
            Iterator<Map.Entry<String, JsonNode>> fields = root.fields();
            while (fields.hasNext()) {
                Map.Entry<String, JsonNode> field = fields.next();
                extract(field.getKey(), field.getValue(), root, results);
            }
        } catch (Exception e) {
            log.error("Failed to parse NovelAI metadata block", e);
            throw new MetadataExtractionException("System failed to parse NovelAI generation parameters from JSON block.", e);
        }
        return results;
    }

    @Override
    public void extract(String key, JsonNode value, JsonNode parentNode, Map<String, String> results) {
        try {
            if (!value.isTextual() && !value.isNumber()) return;

            String text = value.asText().trim();
            if (text.isEmpty()) return;

            if (key.equals("prompt")) {
                if (!results.containsKey("Prompt")) {
                    results.put("Prompt", text);
                }
            } else if (key.equals("uc")) {
                results.put("Negative", text);
            } else if (key.equals("scale")) {
                results.put("CFG", text);
            } else if (key.equals("steps")) {
                results.put("Steps", text);
            } else if (key.equals("seed")) {
                results.put("Seed", text);
            } else if (key.equals("sampler")) {
                results.put("Sampler", text);
            } else if (key.equals("software") && text.equalsIgnoreCase("novelai")) {
                if (!results.containsKey("Model")) {
                    results.put("Model", "NovelAI Diffusion");
                }
            }
        } catch (Exception e) {
            log.error("Error during NovelAI JSON extraction for key: {}", key, e);
        }
    }
}